### ISSUE TITLE
[Todo] 프로젝트 초기설정 사항 및 README 작성사항 목록

### ISSUE THREAD

**Issue by hookor** [FC-Palette/Palette-FE#1]
## ✅ Todos
- [x] **named export** 활용 index.ts 설정 README 추가
- [x] early return, less nesting(if-else)등 **가독성 향상** 요소 README 추가
- [x] return문 렌더링 내 상수 **constants폴더 활용**(export-import) 하드코딩 제거, **이벤트핸들러** return문 상단에 분리
- [x] API함수 작성시 **try-catch중복** 제거
- [x] 초기 컴포넌트 구조설계 논의를 통한 예상 필요 데이터 협의 및 **컴포넌트명에 알맞은 컴포넌트 분리**를 통한 불필요한 상태관리 최소화

**Comment by hookor** [comment]
추가 - 상수폴더링은 컴포넌트 폴더링과 동일하게 생성

**Comment by hookor** [comment]
추가 - ts는 카멜케이스, tsx는 파스칼케이스
