### ISSUE TITLE
[FEAT] 중고거래 공동거래 상세페이지

### ISSUE THREAD

**Issue by leechanghwi** [FC-Palette/Palette-FE#101]
## ✅ Todos
- [X] 공동구매 헤더 조건별 출력
- [X] 공동구매 이미지
- [ ] 공동구매 팔로워
- [X] 공동구매 제목
- [X] 공동구매 금액
- [X] 공동구매 상세정보
- [X] 공동구매 카테고리
- [X] 공동구매 모임정보
- [X] 공동구매 url
- [X] 공동구매 푸터 조건별 출력
- [X] 중고거래 헤더 조건별 출력
- [X] 중고거래 이미지
- [ ] 중고거래 팔로워
- [X] 중고거래 제목
- [X] 중고거래 금액
- [X] 중고거래 상세정보
- [X] 중고거래 카테고리
- [X] 중고거래 모임정보
- [X] 중고거래 작성자카드
- [X] 공동구매 푸터 조건별 출력
