### ISSUE TITLE
[FEAT] 공동구매 중고구매 api연동

### ISSUE THREAD

**Issue by leechanghwi** [FC-Palette/Palette-FE#113]
## ✅ Todos
- [X] 공동구매 리스트 api연동
- [X] 공동구매 포스트 api연동 
- [X] 공동구매 삭제 api연동
- [X] 공동구매 마감 api연동
- [X] 공동구매 상세보기 api연동
- [ ] 공동구매 수정 api연동
- [X] 공동구매 좋아요 api연동
- [X] 공동구매 좋아요취소 api연동
- [X] 공동구매 참여하기 api연동
- [X] 공동구매 필터 api연동
- [X] 중고구매 리스트 api연동
- [X] 중고구매 포스트 api연동 
- [X] 중고구매 삭제 api연동
- [X] 중고구매 마감 api연동
- [X] 중고구매 상세보기 api연동
- [X] 중고구매 좋아요 api연동
- [X] 중고구매 좋아요취소 api연동
- [ ] 중고구매 수정 api연동
- [X] 중고구매 필터 api연동
