### ISSUE TITLE
[Todo] 채팅 잔여 이슈 정리

### ISSUE THREAD

**Issue by hoospacekor** [FC-Palette/Palette-FE#139]
## ✅ Todos

- [ ] **공통 스타일 정리 및 인덱스 모듈 정리 우선 작업** 

- [ ] *Mock Data구성*
- [ ] *시연영상 촬영*
- [ ] *README 작성* => 페이지별 라이브러리 정리 포함

- [ ] 공지 내  모임/상세정보 클릭시 이동  
- [ ] 메시지 클릭시 깜빡거림 수정
- [ ] 멤버 리스트 내 목록에서 상세 프로필로 이동
- [x] 메시지 시간 정보 렌더링 조건 변경 (시간 정보 nextMsg비교가 아닌 prevMsg비교로 변경? ) => Bug
- [ ] 공지 목록 API 값 변경에 따른 닉네임으로 렌더링
- [ ] 모바일 기기 내 ChatField, ChatLsit 영역 높이 값 조정 
- [ ] 푸터 selected 아이콘 추가
- [ ] 알림
