### ISSUE TITLE
[Todo] 마이페이지 잔여 이슈

### ISSUE THREAD

**Issue by dragon-it** [FC-Palette/Palette-FE#141]
## ✅ Todos
- [x] 로그인 페이지 비밀번호 정규식 최신화
- [x] 마이페이지 팔로우 기능 실시간 반영 (useEffect)
- [x] 프로필수정 페이지 이미지 렌더링
- [ ] 알림페이지 mock data 생성 및 적용
- [ ] 팔로우페이지 ui 작업 및 api 리스트 렌더링
- [x] 하단 리스트 api 적용 가능 유무 파악
