### ISSUE TITLE
[Todo] 채팅 주요 컴포넌트 분류

### ISSUE THREAD

**Issue by hookor** [FC-Palette/Palette-FE#34]
## ✅ Todos
- [x] 채팅인풋 (ChatInputField.tsx)
- [x] 채팅방 송신자 (Sender.tsx)
- [x] 채팅방 수신자(Recipient.tsx)
- [x] 채팅방 상단 공지(토글X) (ChatAnn.tsx)
- [x] 모임/상품 정보(토글)  (ChatSubject.tsx)
- [x] 공지 리스팅 페이지(ChatAnnList.tsx)
- [x] 공지 리스팅 아이템(ChatAnnListItem.tsx)
- [x] 공지 상세 페이지(ChatAnnDetail.tsx)
- [x] 채팅 중앙 날짜, 입/퇴장 알림 (ChatNotice.tsx)
- [x] 우측상단 더보기 클릭시 참여인원(ChatMembers.tsx) 
- [ ] 공유시 페이지 미리보기 (구현 미정)

**Comment by hookor** [comment]
- 채팅방 상단 공지(토글X) (ChatAnn.tsx)
 - 모임/상품 정보(토글) (ChatSubject.tsx)
- [ ]  상위 컴포넌트들 부모(ChatInfo.tsx)

**Comment by hookor** [comment]
- [ ] 채팅방 하단 채팅상태 - 모임/거래종료(ChatStatus.tsx)

**Comment by hookor** [comment]
- [ ] 채팅방 인원 목록 우측상단 더보기 클릭시 공지로 이동 (ToChatList.tsx)
