### ISSUE TITLE
[Todo] 마이페이지 -> 설정페이지 라우트, ui 작업

### ISSUE THREAD

**Issue by dragon-it** [FC-Palette/Palette-FE#36]
## ✅ Todos
- [x] 설정 페이지 라우트 지정
- [x] 설정 페이지 상수 정리
- [x] 설정 페이지 ui 컴포넌트 분리
- [x] 설정 페이지 공통 버튼 컴포넌트 분리
- [x] 설정 페이지 비밀번호 변경 ui
- [x] 설정 페이지 오피스 관리 ui
- [x] 설정 페이지 알림 설정 ui
- [x] 설정 페이지 공지사항 ui
- [x] 설정 페이지 고객센터 ui
