### ISSUE TITLE
[Todo] 마이페이지 -> 설정 목록 경로 라우트 및 Ui 작업

### ISSUE THREAD

**Issue by dragon-it** [FC-Palette/Palette-FE#47]
## ✅ Todos
- [x] 설정 페이지 화살표 아이콘 삽입
- [x] 설정 페이지 목록 세부 라우트 경로 설정
- [x] 알림 페이지 생성
- [x] 알림 페이지 라우트 경로 설정
- [x] 알림 페이지 1차 Ui 작업
