### ISSUE TITLE
[Todo] 설정 페이지 ui

### ISSUE THREAD

**Issue by dragon-it** [FC-Palette/Palette-FE#49]
## ✅ Todos
- [x] 설정 페이지 개별 헤더 적용
- [x] 비밀번호 변경 페이지 ui 작업
- [ ] 비밀번호 변경 페이지 정규식 적용
- [x]  알림 설정 페이지 ui 작업
- [x]  오피스 관리 페이지 ui 작업
- [x]  공지사항 페이지 ui 작업
- [x]  고객센터 페이지 ui 작업
