### ISSUE TITLE
[Todo] UI 수정 및 보안

### ISSUE THREAD

**Issue by dragon-it** [FC-Palette/Palette-FE#80]
## ✅ Todos
- [x] 오피스 관리 메뉴 UI 블럭 처리
- [x] 헤더 영역 뒤로 가기 라우트 설정
- [x] 로그인 페이지 초기 정규식 출력 x
- [x] 정규식에 icon 삽입
- [x] 마이페이지 설정, 알림 아이콘 색상 변경
- [x] 프로필 수정하기 페이지 라우팅
- [x] 지금 모임 시작하기 페이지 라우팅 
- [x] 푸터 영역 해당 페이지일 때 색상 변화
