### ISSUE TITLE
[Todo] API 전쟁 대비를 위한 더미 파일 생성 및 적용 작업

### ISSUE THREAD

**Issue by dragon-it** [FC-Palette/Palette-FE#89]
## ✅ 전쟁 시작 전 필수 이행 사전 작업🏴‍☠️
- [ ] 로그인 API 더미 파일 생성
- [ ] 더미 파일 API 연결 및 access token 로컬 저장
- [ ] 로그인 성공시 home 페이지 라우트
- [ ] 유저 정보 마이페이지 API 더미 파일 생성
- [ ] 마이페이지에 유저 정보 더미 파일 연결 및 렌더링 
- [ ] 프로필 수정하기 ui 작업
- [ ] 알림 페이지 모두 읽음 누르면 읽음 표시 되게 처리
- [ ] 공지, 설문조사 카테고리 분류 작업
- [ ] 카테고리 별 미리보기 아이콘 표시 작업
- [ ] 클릭 및 읽은 알림은 투명도 50% 처리
- [ ] 같이 성장해요, 같이 사요 카테고리 분류 작업
