### ISSUE TITLE
[FEAT] 필터사이드바 구현

### ISSUE THREAD

**Issue by leechanghwi** [FC-Palette/Palette-FE#94]
## ✅ Todos
- [X] 공통 필터사이드바 전체UI
- [X] 공통 필터사이드바 금액컴포넌트
- [X ] 공통 필터사이드바 선택시 css변경
- [X] 공통 필터사이드바 선택시 카테고리 필터바와 연동
- [X] 공통 필터사이드바 선택시 검색개수
